indent_style = "Block"
use_small_heuristics = false
comment_width = 100
control_brace_style = "AlwaysSameLine"
fn_args_density = "Vertical"
brace_style = "SameLineWhere"
where_single_line = true
max_width=100
imports_indent="Block"
match_block_trailing_comma=true
merge_derives=false
reorder_imports_in_group=true
reorder_extern_crates_in_group=true
reorder_modules=true
tab_spaces=2
use_try_shorthand=true